### ISSUE TITLE
support for .NET Framework 4?

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Management#50]
Assuming the codebase impact would be minimal (or even non existing), would the maintainers of this library accept a patch to make it target Framework 4?

**Comment by vasily-kirichenko** [comment]
I don't mind.

**Comment by dsyme** [comment]
@smoothdeveloper - Yes, that's fine, unless it reduces functionality.  You can also add both net40 and net45 assemblies in the nuget packages.

**Comment by smoothdeveloper** [comment]
I can give a try at multiplatform targetting but I'm not used to nuget packaging affairs.

Would someone point me to a not too big project which supports that so I can give it a shot?

Thanks!

**Comment by dsyme** [comment]
It's ok just to use "net40" if it works

**Comment by sergey-tihon** [comment]
Should be fixed by this PR https://github.com/fsprojects/FSharp.Management/pull/52
