### ISSUE TITLE
Unexpected number of result types '8'

### ISSUE THREAD

**Issue by camkego** [fsprojects/FSharp.Management#53]
Sorry, I cannot help more, I am a F# newbie.
Trying to explore the Powershell type provider, but I get an error when setting up.
Any clues what to do next?
Thanks
Cameron

-- FSI output -- 

--> Referenced 'C:\Users\c\Documents\Visual Studio 2013\Projects\fsharp play\packages\FSharp.Management.0.2.0\lib\net40\FSharp.Management.PowerShell.dll' (file may be locked by F# Interactive process)

Binding session to 'C:\Users\c\Documents\Visual Studio 2013\Projects\fsharp play\fsharp play\bin\Debug\System.Management.Automation.dll'...

Script1.fsx(13,11): error FS3021: Unexpected exception from provided type 'FSharp.Management.PowerShellProvider,PSSnapIns="",Is64BitRequired="False"' member 'GetMethods': The type provider 'FSharp.Management.PowerShellProvider.PowerShellProvider' reported an error: Unexpected number of result types '8'
>

**Comment by sergey-tihon** [comment]
Could you provide code sample that you have tried to execute?

**Comment by camkego** [comment]
Sorry, I thought I had included it.

These are the lines:

#I @"C:\Users\c\Documents\Visual Studio 2013\Projects\fsharp play\packages\FSharp.Management.0.2.0\lib\net40"

#I @"C:\Users\c\Documents\Visual Studio 2013\Projects\fsharp play\fsharp play\bin\Debug"


#r "System.Management.Automation.dll"
#r "FSharp.Management.PowerShell.dll"

open FSharp.Management

// Let the type provider infer the signatures of available cmdlets
type PS = PowerShellProvider< PSSnapIns="", Is64BitRequired=false >

PS.``Get-EventLog``(logName="Application", entryType=[|"Error"|], newest=2)

**Comment by sergey-tihon** [comment]
Please try [latest package from NuGet](https://www.nuget.org/packages/FSharp.Management/0.2.1)
This issue should be fixed

**Comment by sergey-tihon** [comment]
Please test it and reopen this issue if needed
