### ISSUE TITLE
Add SystemTimeZonesProvider 

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Management#55]
I'm not sure but seems like FSharp.Management can be good host for SystemTimeZonesProvider.
https://github.com/dmitry-a-morozov/Sandbox/tree/master/SystemTimeZonesProvider

**Comment by forki** [comment]
Sounds good to me

**Comment by dsyme** [comment]
+1

**Comment by vasily-kirichenko** [comment]
:+1:

**Comment by dmitry-a-morozov** [comment]
I will submit PR.

**Comment by sergey-tihon** [comment]
Closed via https://github.com/fsprojects/FSharp.Management/pull/56
