### ISSUE TITLE
using Hyper-V PowerShell modules

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/FSharp.Management#64]
I'm having trouble getting FSharp.Management 0.3.1 working with Hyper-V PowerShell modules. Both the `1.1` and `2.0` modules get installed on Windows 10 when you do:
``` powershell
Enable-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Management-PowerShell -Online -All
```
I'm interested in `1.1` because they are compatible with Windows Server 2012 Hyper-V. On Windows 10, you can switch to the older version by doing:
``` powershell
Remove-Module Hyper-V
Import-Module "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Hyper-V\1.1\Hyper-V.psd1"
```
An example command is to get information about the VHD (virtual hard disk) of a VM. This works via PowerShell:
``` powershell
Get-VHD -ComputerName it-1 -Id 63915ae2-86ca-407f-b2c7-0ddfe22cb241
```
The problem is that I get `null` back from the TypeProvider with any of the Hyper-V commands I've tried so far like:
``` fsharp
open FSharp.Management
open System

let [<Literal>] mHyperV = @"C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Hyper-V\1.1\Hyper-V.psd1"

type HyperV = PowerShellProvider<mHyperV>

[<EntryPoint>]
let main argv = 
    let vhd = HyperV.``Get-VHD``([|Guid("63915ae2-86ca-407f-b2c7-0ddfe22cb241")|], computerName=[|"it-1"|])
    printfn "vhd: %A" vhd
    0
```
Any ideas what I'm doing wrong?

**Comment by ctaggart** [comment]
I have a pretty good idea what is wrong and may be able to contribute back soon.

**Comment by ctaggart** [comment]
I tried troubleshooting this. I figured out how to debug it. I tried to run an `Import-Module` after opening the runspace and I get this error accessing the registry with the PSRuntimeHosted.

![image](https://cloud.githubusercontent.com/assets/80104/11293507/8e8f5a84-8f0f-11e5-9f25-3d4b7efd377f.png)

Any idea how to get around that? May be there is a way to disable the log provider.

**Comment by ctaggart** [comment]
Backing up a bit, there is a problem in `HostedRuntime.fs`. The `ResultObjectTypes` is emtpy.

![image](https://cloud.githubusercontent.com/assets/80104/11293576/02eb8fa6-8f10-11e5-800e-efa29d4264c8.png)

**Comment by ctaggart** [comment]
I [hacked on it for a while](https://github.com/fsprojects/FSharp.Management/compare/master...ctaggart:hack1), but no luck yet. The `Get-Command` `OutputType` property ends up being an empty collection for many of the Hyper-V commands. I looped through all the thrown exceptions and a `PSArgumentException` is thrown that looks suspicious. 

![image](https://cloud.githubusercontent.com/assets/80104/11317309/7f6dbec6-8fdf-11e5-932c-5832dbef88f0.png)

![image](https://cloud.githubusercontent.com/assets/80104/11317313/89ebea44-8fdf-11e5-9961-a808747bdd76.png)

**Comment by sergey-tihon** [comment]
It is not clear why you get `null`
As I remember if TP cannot infer result type, we set it to PSObject list.
So after execution you should receive everything that command returned

**Comment by Firgeis** [comment]
Sadly, I don't have a way to properly test this. @ctaggart could you give it another go?

**Comment by ctaggart** [comment]
I'm on Mac & Linux almost full time now, so I'm going to close this. If someone else is interested, please reopen.
