### ISSUE TITLE
Build script fails

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Management#72]
Running build.cmd fails with

Paket version 3.0.0.0
unrecognized argument: '--hard'.

**Comment by voronoipotato** [comment]
Hey I was able to build just fine. What have you tried so far? Were you ever able to figure out what was wrong with your set-up?

**Comment by sergey-tihon** [comment]
Builds are green and works just fine on my machine too.
I close it for now, please reopen if it still does not work on your machine
