### ISSUE TITLE
Please update ProvidedTypes.fs for Mono 5.0 

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Management#82]
Please update to use the latest version of ProvidedTypes.fs, as described in  https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121

Many thanks

**Comment by sergey-tihon** [comment]
Released as [v0.4.5](https://www.nuget.org/packages/FSharp.Management?NormalizedVersion=0.4.5)
